### ISSUE TITLE
Favicon no existe

### ISSUE THREAD

**Issue by SciProgrammist** [alexyslozada/shorturl-react#7]
En el archivo index.html se esta llamando al favicon pero este no existe en la carpeta src. Necesitas ayuda creando el favicon?

**Comment by LuisRey66** [comment]
Que tal buenas noches Amigo,

Una disculpa, a que se refiere este correo? de gitHub, ando un poco
perdido, o no se si me inscribi algún curso?

Saludos

**Comment by SciProgrammist** [comment]
Hola! Luis, 

Jajaja mil disculpas, estoy terminando el curso de Edteam que es sobre Github Para programadores, y como a mi me gusta ir haciendo las mismas cosas que hace el instructor entonces en un proyecto del profesor Alexys se uso como prueba para aprender a usar la herramienta de Github, y no sabía que te caían correos, pero solo fue practica nada mas, ya termine el curso.

**Comment by LuisRey66** [comment]
a ok ok, perfecto jejeje no te preocupes

Saludos.

**Comment by SciProgrammist** [comment]
Sí, sabes, me encanta esto que en GitHub no solo compartimos código, sino que también podemos hablar entre nosotros, siento bien esta idea de que se ha mantenido bien el origen de ser una Red Social para programadores, sin perder el enfoque inicial que es el codificar.

**Comment by LuisRey66** [comment]
Así es Amigo, Consulta en que lenguaje te estas desarrollando?

Saludos!

**Comment by SciProgrammist** [comment]
Por mi universidad domino las tecnologías de un desarrollador .NET, pero por mis pasantías en un Banco Local me he puesto a estudiar mucho Java y me especializaré en esa tecnología, ya que me darán 2 meses de capacitación para poder cubrir su necesidad de ingenieros Backend y otros 2 para solucionarles una necesidad en un proyecto dirigido por el banco.
